### ISSUE TITLE
Comparing to BetterChatGPT

### ISSUE THREAD

**Issue by bitsnaps** [imabutahersiddik/Ultimate-ChatGPT#23]
Hi, Can you tell me what makes this project different from [BetterChatGPT](https://github.com/ztjhz/BetterChatGPT) or even better [ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web), if you want to extend the later, why don't just you fork then add your new features?

**Comment by imabutahersiddik** [comment]
I will try to add new feature to decentralized whole conversation of ai on BetterChatGPT, which will make conversation uneraseable. 
Thank you for your recommendation.
