### ISSUE TITLE
Instructions to install on Linux

### ISSUE THREAD

**Issue by helsingi** [imabutahersiddik/Ultimate-ChatGPT#26]
Can we please have the instructions on how to install this app locally on a Linux OS?
I understand the provided installation method using "vercel" might be user friendly but I do not want to register an account somewhere and access the app online, I want to install and run it locally only. Thanks

**Comment by imabutahersiddik** [comment]
Here you can read linux installation guide: [Linux installation guide of Ultimate ChatGPT](https://github.com/imabutahersiddik/Ultimate-ChatGPT#-local-installation-guide)
